name: dice

description: Roll as many dices as you want!

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/dice_1.png
    - assets/images/dice_2.png
    - assets/images/dice_3.png
    - assets/images/dice_4.png
    - assets/images/dice_5.png
    - assets/images/dice_6.png
    - assets/icons/launcher_icon.png
